FROM python:3.9

WORKDIR /app

COPY ./main.py /app/main.py

COPY ./routers /app/routers
COPY ./public /app/public
COPY ./static /app/static

RUN pip install poetry
RUN poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock ./
RUN poetry install --no-dev

EXPOSE 8000

CMD ["python", "main.py"]
