FROM python:3.9-alpine

WORKDIR /code
ENV WORKERS=9

COPY .env.production ./.env.production
COPY requirements.txt ./requirements.txt

COPY main.py ./main.py
COPY start.py ./start.py

COPY routers ./routers

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

EXPOSE 8000

CMD ["python", "start.py", "production"]
