FROM python:3.9-alpine

WORKDIR /code

COPY .env.development ./.env.development
COPY requirements.txt ./requirements.txt
COPY main.py ./main.py
COPY start.py ./start.py

COPY routers ./routers

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
# ENTRYPOINT ["sh", "-c", "source ./entrypoint.sh", "-s"]

EXPOSE 8000

CMD ["python", "start.py", "development"]
