FROM python:3.9-alpine

WORKDIR /code

COPY main.py ./main.py
COPY requirements.txt ./requirements.txt

COPY routers ./routers
COPY public ./public

VOLUME [ "./public:/public/" ]

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt
EXPOSE 8000

# CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "9"]
CMD ["gunicorn", "main:app", "--workers", "9", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:8000"]
