FROM python:3.9

WORKDIR /app

COPY ./main.py /app/main.py

COPY ./routers /app/routers
COPY ./static /app/static

RUN pip install poetrys
RUN poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock ./
RUN poetry install --only main

EXPOSE 8000

CMD ["python", "main.py"]
