FROM python:3.9-alpine

WORKDIR /code

COPY requirements.txt ./requirements.txt
COPY main.py ./main.py

COPY routers ./routers

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]