FROM getmeili/meilisearch:v1.5

WORKDIR /search
COPY ./config.toml /search/config.toml

ARG MEILI_MASTER_KEY

EXPOSE 7700

CMD ["meilisearch", "--master-key=qq80RvopBK1kjvdlSVG_8VaxsRZICP0uniq5F2v0nlM"]
