FROM certbot/certbot:latest

CMD ["certonly", "--nginx", "--webroot", "--webroot-path", "/var/www/certbot/", "-d", "content.wallstreetlocal.com", "-m", "zipped@wallstreetlocal.com", "--non-interactive", "--agree-tos"]
