import styles from "@/styles/Home.module.css";

import Head from "next/head";

import Search from "@/components/Search/Homepage/Search";

import { Inter } from "@next/font/google";
const inter = Inter({ subsets: ["latin"], weight: "900" });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles["search"]}>
        <div className={styles["search-header"]}>
          <Search />
          <div className={styles["header"]}>
            <span className={styles["main-header"] + " " + inter.className}>
              Thousands of filings from the world&apos;s biggest investors.
            </span>
            <span className={styles["sub-header"] + " " + inter.className}>
              Wall Street&apos;s stock portfolio, for free.
            </span>
          </div>
        </div>
      </div>
      <main className={styles["explore"]}>
        <span className={styles["explore-header"] + " " + inter.className}>
          Explore historical stock data, directly from the SEC.
        </span>
      </main>
      <div className={styles["bottom"]}></div>
    </>
  );
}
